import { StyleSheet } from 'react-native';

/** Paleta da logo Sintonia */
const BRAND_BG = '#F5EFFB';
const BRAND_PRIMARY = '#262626';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BRAND_BG,
    paddingHorizontal: 24,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 72,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: BRAND_PRIMARY,
    marginBottom: 20,
    textAlign: 'center',
  },
  photoWrap: {
    alignSelf: 'center',
    marginBottom: 20,
  },
  photo: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#E5DDF0',
  },
  photoPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoEditWrap: {
    alignItems: 'center',
    marginBottom: 8,
  },
  editPhotoButton: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: '#E5DDF0',
    borderRadius: 20,
  },
  editPhotoButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: BRAND_PRIMARY,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  dataRow: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EBF5',
  },
  dataLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#5C4D6B',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dataValue: {
    fontSize: 16,
    color: BRAND_PRIMARY,
  },
  logoutButton: {
    marginTop: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: '#D4C4E8',
    borderRadius: 12,
    alignSelf: 'center',
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: BRAND_PRIMARY,
  },
  editButton: {
    marginTop: 16,
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: '#6C26CB',
    borderRadius: 12,
    alignSelf: 'center',
  },
  editButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  formField: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#5C4D6B',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  formInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 18,
    fontSize: 17,
    color: BRAND_PRIMARY,
  },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  phoneCountryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    minWidth: 88,
  },
  phoneCountryText: {
    fontSize: 17,
    fontWeight: '600',
    color: BRAND_PRIMARY,
  },
  phoneInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 18,
    fontSize: 17,
    color: BRAND_PRIMARY,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 12,
  },
  segment: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentSelected: {
    backgroundColor: '#6C26CB',
    borderColor: '#6C26CB',
  },
  segmentText: {
    fontSize: 15,
    fontWeight: '600',
    color: BRAND_PRIMARY,
  },
  segmentTextSelected: {
    color: '#FFFFFF',
  },
  optionColumn: {
    gap: 12,
  },
  optionBig: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
  },
  optionBigSelected: {
    backgroundColor: '#6C26CB',
    borderColor: '#6C26CB',
  },
  optionBigText: {
    fontSize: 16,
    fontWeight: '600',
    color: BRAND_PRIMARY,
  },
  optionBigTextSelected: {
    color: '#FFFFFF',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  tag: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
  },
  tagSelected: {
    backgroundColor: '#6C26CB',
    borderColor: '#6C26CB',
  },
  tagText: {
    fontSize: 14,
    fontWeight: '600',
    color: BRAND_PRIMARY,
  },
  tagTextSelected: {
    color: '#FFFFFF',
  },
  rowButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
    justifyContent: 'center',
  },
  saveButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    backgroundColor: '#6C26CB',
    borderRadius: 12,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  cancelButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    backgroundColor: '#E5DDF0',
    borderRadius: 12,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: BRAND_PRIMARY,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalBox: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: 320,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: BRAND_PRIMARY,
  },
  countryOption: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  countryOptionText: {
    fontSize: 16,
    color: BRAND_PRIMARY,
    fontWeight: '500',
  },
  gallerySection: {
    marginBottom: 24,
  },
  gallerySectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5C4D6B',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  galleryItem: {
    width: '31%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#E5DDF0',
  },
  galleryItemImage: {
    width: '100%',
    height: '100%',
  },
  galleryAddCell: {
    width: '31%',
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: '#E5DDF0',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#6C26CB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryAddCellContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryRemoveBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
});
